builds:
- id: "srv-account"
  binary: srv-account
  main: ./cmd/srv/account.go
  goos:
#  - windows
  - darwin
  - linux
  - freebsd
  goarch:
  - amd64
  - 386
#  - arm
#  - arm64
  goarm:
#  - 6
#  - 7
- id: "srv-user"
  binary: srv-user
  main: ./cmd/srv/user.go
  goos:
  - linux
  - freebsd
  goarch:
  - amd64
  - 386
  goarm:
archives:
- id: default
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    darwin: macOS
#    windows: Windows
#    386: i386
#    amd64: x86_64
  format_overrides:
  - goos: windows
    format: zip
checksum:
  name_template: "checksums.txt"
  algorithm: sha256