apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api-backend
spec:
  hosts:
  - "*"
  gateways:
  - user-gateway
  http:
  - match:
    #    - uri:
    #        exact: /login
    #    - uri:
    #        exact: /logout
      - uri:
          prefix: /backend/
      route:
      - destination:
          host: api-backend
          port:
            number: 8888
    corsPolicy:
      allowOrigin:
      - "*"
      allowMethods:
      - POST
      - GET
      - DELETE
      - PUT
      - PATCH
      - OPTIONS
      - HEAD
      allowCredentials: false
      allowHeaders:
      - Content-Type
      - Accept
      - Authorization
    #      maxAge: "24h"
    #          weight: 100
    #    - destination:
    #        host: api-statis
    #        subset: v2
    #        port:
    #          number: 8888
    #      weight: 50


