#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: test-name
#  namespace: default
#---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
namespace: default
  name: srv-user-v1
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: srv-user
        version: v1
    spec:
#      serviceAccountName: test-name
#      imagePullSecrets:
#      - name: registry-secret
      containers:
      - name: srv-user
        env:
        - name: CONFIGOR_TRACE_ADDRESS
          value: jaeger-agent:6831
#        - name: CONFIGOR_SERVICE_NAME
#          value: srv-user
        - name: CONFIGOR_MYSQL_DBNAME
          value: user
        - name: CONFIGOR_MYSQL_ADDR
          value: mysqladdr
        - name: CONFIGOR_MYSQL_USER
          value: test
        - name: CONFIGOR_MYSQL_PASSWORD
          value: test
        - name: RAND_NUM
          value: num17994
#        command: [
#          "/srv_user",
#        ]
        image: srv-user:v1.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5001


---
apiVersion: v1
kind: Service
metadata:
  name: srv-user
namespace: default
  labels:
    app: srv-user
spec:
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    app: srv-user
#  type: LoadBalancer
#  type: NodePort