#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: test-name
#  namespace: default
#---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
namespace: default
  name: srv-socket-v1
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: srv-socket
        version: v1
    spec:
#      serviceAccountName: test-name
#      imagePullSecrets:
#      - name: registry-secret
      containers:
      - name: srv-socket
        env:
        - name: CONFIGOR_TRACE_ADDRESS
          value: jaeger-agent:6831
#        - name: CONFIGOR_SERVICE_NAME
#          value: srv-socket
        - name: CONFIGOR_MYSQL_DBNAME
          value: socket
        - name: CONFIGOR_MYSQL_ADDR
          value: mysqladdr
        - name: CONFIGOR_MYSQL_socket
          value: test
        - name: CONFIGOR_MYSQL_PASSWORD
          value: test
        - name: RAND_NUM
          value: num17994
#        command: [
#          "/srv_socket",
#        ]
        image: srv-socket:v1.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5002


---
apiVersion: v1
kind: Service
metadata:
  name: srv-socket
namespace: default
  labels:
    app: srv-socket
spec:
  ports:
  - port: 5002
    protocol: TCP
    targetPort: 5002
  selector:
    app: srv-socket
#  type: LoadBalancer
#  type: NodePort