apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: srv-socket
spec:
  hosts:
  - srv-socket
  http:
  - route:
    - destination:
        host: srv-socket
        subset: v1

