#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: test-name
#  namespace: default
#---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: api-frontend-v1
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: api-frontend
        version: v1
    spec:
#      serviceAccountName: test-name
#      imagePullSecrets:
#      - name: registry-secret
      containers:
      - name: api-frontend
        env:
        - name: CONFIGOR_TRACE_ADDRESS
          value: jaeger-agent:6831
        - name: CONFIGOR_SRVUSER_ADDRESS
          value: srv-user:5001
        - name: RAND_NUM
          value: num179d94
#        command: [
#          "/api_frontend",
#        ]
        image: api-frontend:v1.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8889


---
apiVersion: v1
kind: Service
metadata:
  name: api-frontend
  namespace: dev
  labels:
    app: api-frontend
spec:
  ports:
  - port: 8889
    protocol: TCP
    targetPort: 8889
  selector:
    app: api-frontend
#  type: LoadBalancer
#  type: NodePort