#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: test-name
#  namespace: default
#---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: api-backend-v1
spec:
  replicas: 2
  template:
apiVersion: v1
kind: Service
metadata:
  name: api-backend
  namespace: dev
  labels:
    app: api-backend
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: api-backend
#  type: LoadBalancer
#  type: NodePort
